Server = 'tcp:bluecroftsql-server.database.windows.net'
Port = 1433
Database = 'CarStatus'
UserName = ''
Password = ''
Encrypt="yes"
TrustServerCertificate="no"
ConnectionTimeout=30
Authentication="Active Directory Password"
